### ISSUE TITLE
An error occurred. Please try again later.

### ISSUE THREAD

**Issue by estatistics** [yasinatesim/facebook-album-downloader#1]
"An error occurred. Please try again later."

the program is running in localhost. 
 post the public link of fb album https://www.facebook.com/media/set/?set=a.452646741429651&type=3
but it does says error

**Comment by yasinatesim** [comment]
Hey @estatistics 👋

I tried your album link, but I didn't see an error.

Please check your node version, my node version is 18.18.0 but, it also works on version 16.0.0+ and 17.0.0. I tried the versions and I didn't get an error. 

Please check the video 👇

https://github.com/yasinatesim/facebook-album-downloader/assets/32565521/2a01a1cd-3f5e-4082-8440-1c0febea49f8

**Comment by estatistics** [comment]
```
⨯ Error: Could not find Chromium (rev. 1108766). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:263:27)
    at ChromeLauncher.executablePath (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.computeLaunchArguments (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:93:37)
    at ChromeLauncher.launch (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:57:39)
    at ChromeLauncher.launch (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:47:22)
    at PuppeteerNode.launch (file:///home/eros/Downloads/_linux/facebook-album-downloader/node_modules/puppeteer-core/lib/esm/puppeteer/node/PuppeteerNode.js:147:105)
    at handler (webpack-internal:///(api)/./pages/api/download/index.ts:33:77)
    at /home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/next-server/pages-api.runtime.dev.js:21:3039
    at /home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/server/lib/trace/tracer.js:106:107
    at NoopContextManager.with (/home/eros/Downloads/_linux/facebook-album-downloader/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057) {
  page: '/api/download'
}
```

the cache folder on debian linxu is indeed `~/.cache/puppeteer/chrome/linux-117.0.5938.92`
node
v18.13.0
npm
9.2.0
yarn -v
1.22.19

**Comment by estatistics** [comment]
i tried clean install with both npm and yarn not worked.

I tried the suggestion but not worked
PUPPETEER_CACHE_DIR=$(pwd) npm install puppeteer
PUPPETEER_CACHE_DIR=$(pwd) node <script-path>
(in order to change folder to /home/user/.cache)

i dont know how to declare a cache folder in instalation, running or even as config file in puppeeter 
see here: https://pptr.dev/guides/configuration
(i ran sudo yarn dev)

**Comment by estatistics** [comment]
SOLVED 
path was `/home/USER/.cache/puppeteer/chrome/linux-117.0.5938.92/chrome-linux64/`
path copied as `/home/USER/.cache/puppeteer/chrome/linux-1108766/chrome-linux/`

Please add in script to print the expected path that puppeeter is searching chromium. 

note that running as `sudo yarn dev` is searching in root/.cache while `yarn dev`
but the latest was throwing errors 

So,  `sudo npm run build --loglevel=error` or  `sudo yarn run build --loglevel=error` and then `yarn start` or `npm start`
